# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_text',
            new_name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.Post'),
            preserve_default=False,
        ),
    ]
